### ISSUE TITLE
NumberFormatException when deserializing specific member constellation

### ISSUE THREAD

**Issue by nis73** [Stuart-campbell/RushOrm#34] opened 2015-05-07 16:03 UTC
Hi, I'm having an onject similar to the following one:

    public class MyObject extends RushObject {

        public static final int CONST = 0;
        private int firstInt = 30;
        private boolean firstBool = false;

        public MyObject() {
        }
    }

When I write the object to the database and read it again, like in this code ...

    public class MainActivity extends ActionBarActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            MyObject obj = new MyObject();
            obj.save();
            System.out.println("saved object");
            System.out.println(new RushSearch().find(MyObject.class));
        }
    }

... I get a NumberFormatException: 

    05-07 17:52:44.110  19742-19742/de.test.testrushorm E/AndroidRuntime﹕ FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{de.test.testrushorm/de.test.testrushorm.MainActivity}: java.lang.NumberFormatException: Invalid int: "false"
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2103)
                at android.app.ActivityThread.access$600(ActivityThread.java:137)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
                at android.os.Handler.dispatchMessage(Handler.java:99)
                at android.os.Looper.loop(Looper.java:137)
                at android.app.ActivityThread.main(ActivityThread.java:4827)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:511)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                at dalvik.system.NativeStart.main(Native Method)
         Caused by: java.lang.NumberFormatException: Invalid int: "false"
                at java.lang.Integer.invalidInt(Integer.java:138)
                at java.lang.Integer.parse(Integer.java:375)
                at java.lang.Integer.parseInt(Integer.java:366)
                at java.lang.Integer.parseInt(Integer.java:332)
                at co.uk.rushorm.core.implementation.RushColumnInt.deserialize(RushColumnInt.java:22)
                at co.uk.rushorm.core.implementation.RushColumnInt.deserialize(RushColumnInt.java:9)
                at co.uk.rushorm.core.implementation.RushColumnsImplementation.setField(RushColumnsImplementation.java:50)
                at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClass(ReflectionClassLoader.java:99)
                at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:54)
                at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:42)
                at co.uk.rushorm.core.RushCore.load(RushCore.java:577)
                at co.uk.rushorm.core.RushCore.load(RushCore.java:232)
                at co.uk.rushorm.core.RushSearch.find(RushSearch.java:40)
                at de.test.testrushorm.MainActivity.onCreate(MainActivity.java:22)
                at android.app.Activity.performCreate(Activity.java:5013)
                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2042)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2103)
                at android.app.ActivityThread.access$600(ActivityThread.java:137)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
                at android.os.Handler.dispatchMessage(Handler.java:99)
                at android.os.Looper.loop(Looper.java:137)
                at android.app.ActivityThread.main(ActivityThread.java:4827)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:511)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                at dalvik.system.NativeStart.main(Native Method)

The curious thing is that this happens only in the class member constellation given above. If I either omit the Integer, the Boolean or the constant - it works :)
One more information: The problem encountered since version 1.1.3.

Thanks in advance.

**Comment by Stuart-campbell** [comment] 2015-05-07 18:22
Hi,

I can't seem to reproduce this. Is rush_debug true?

Thanks

**Comment by nis73** [comment] 2015-05-08 08:25
Hi, 

yes, rush_debug is true. The crash occures on a Huawei G525. I tested it on a XPeria Z3 now and there it works. Really strange. I'm going to test it on some other devices.

**Comment by Stuart-campbell** [comment] 2015-05-08 08:47
Is there any change that one of your variables type was redefined at some point? The migration does not support changing type. Might be worth fully uninstalling and reinstalling to rule that out.

**Comment by nis73** [comment] 2015-05-08 08:58
No, I'm using the example described above - only the MyObject class and the code from MainActivity, and it is reproducable after full uninstall. Is it helpful if I send you the example code?

**Comment by Stuart-campbell** [comment] 2015-05-08 09:06
Yeah I can take a look. Don't have access to a Huawei G525 lots of samsung and htcs but no Huawei.

**Comment by nis73** [comment] 2015-05-08 10:24
I was able to reproduce the error on a Samsung SM-T315 (Galaxy Tab) now.
Could it be related to the Android version? The Huawei phone has Android 4.1.2 and the Samsung tablet has 4.4.2.

**Comment by Stuart-campbell** [comment] 2015-05-08 10:32
The sqlite version did change from 3.7 to 3.8 between those Android version. I'll have a proper look into it and get back to you.

**Comment by Stuart-campbell** [comment] 2015-05-09 13:09
Found the cause of this bug, was because of the final static. Should have a fix this weekend.

Thanks

**Comment by Stuart-campbell** [comment] 2015-05-11 18:59
Hi,

This should now be fixed in 1.1.5

Cheers

**Comment by nis73** [comment] 2015-05-12 10:33
It works now. Thanks for the quick fix.

**Closed** 2015-05-12 20:55 UTC
Labels: bug
